server:
    port: 8091
    servlet:
      context-path: /api

      To log values:

logging:
    level:
        org.hibernate.type: trace

spring:
  application-name: "Gestion tion des taches"
  liquibase:
    change-log: classpath:db/changelog/changelog.sql
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3316/gestion-taches
    username: root
    password: mdp
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  header: "Authorization"
  infos: "USER_INFOS"
  secret: "AL_KEY"
  expiration: 3600 # (secondes) == 1 heure
  route:
    authentication:
      path: "/login"
      refresh: "/refresh"

