-- liquibase formatted sql

-- changeset Achille:1
CREATE TABLE EMPLOYEE (
    ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(200),
    LAST_NAME VARCHAR(200),
    USERNAME_NAME VARCHAR(200),
    PRIMARY KEY (ID)
);
CREATE TABLE TASK (
      ID INT NOT NULL AUTO_INCREMENT,
      TITLE VARCHAR(200),
      DESCRIPTION TEXT,
      INITIAL_TIME numeric,
      REMAINING_TIME numeric,
      PRIMARY KEY (ID)
);
CREATE TABLE EMPLOYEE_TASK (
      EMPLOYEE_ID INT,
      TASK_ID INT,
      PRIMARY KEY (EMPLOYEE_ID, TASK_ID),
      FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
      FOREIGN KEY (TASK_ID) REFERENCES TASK(ID)
);

-- changeset EMPLOYE_44:2
CREATE TABLE ROLE (
      ID INT NOT NULL AUTO_INCREMENT,
      LABEL VARCHAR(200),
      PRIMARY KEY (ID)
);
