-- liquibase formatted sql

-- changeset Achille:1
CREATE TABLE EMPLOYEE (
    ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(200),
    LAST_NAME VARCHAR(200),
    USERNAME_NAME VARCHAR(200),
    PRIMARY KEY (ID)
);
CREATE TABLE TASK (
      ID INT NOT NULL AUTO_INCREMENT,
      TITLE VARCHAR(200),
      DESCRIPTION TEXT,
      INITIAL_TIME numeric,
      REMAINING_TIME numeric,
      PRIMARY KEY (ID)
);
CREATE TABLE EMPLOYEE_TASK (
      EMPLOYEE_ID INT,
      TASK_ID INT,
      PRIMARY KEY (EMPLOYEE_ID, TASK_ID),
      FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
      FOREIGN KEY (TASK_ID) REFERENCES TASK(ID)
);

-- changeset EMPLOYE_44:2
CREATE TABLE ROLE (
      ID INT NOT NULL AUTO_INCREMENT,
      LABEL VARCHAR(200),
      PRIMARY KEY (ID)
);


-- changeset EMPLOYE_44:3
ALTER TABLE EMPLOYEE ADD COLUMN PASSWORD VARCHAR(255);

-- changeset EMPLOYE_44:4
ALTER TABLE EMPLOYEE ADD COLUMN ENABLED boolean;


-- changeset EMPLOYE_44:5
CREATE TABLE EMPLOYEE_ROLE (
      EMPLOYEE_ID INT NOT NULL,
      ROLE_ID INT NOT NULL,
      PRIMARY KEY (EMPLOYEE_ID, ROLE_ID),
      FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
      FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);
INSERT into ROLE(label) values ('ADMIN');
INSERT into ROLE(label) values ('USER');
INSERT into ROLE(label) values ('MANAGER');


-- changeset EMPLOYE_44:6
CREATE TABLE CONFIRMATION_TOKEN (
    ID INT NOT NULL AUTO_INCREMENT,
    value varchar(6),
    creation timestamp,
    EMPLOYEE_ID INT NOT NULL,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),

    PRIMARY KEY (ID)
);


-- changeset EMPLOYE_44:7
ALTER TABLE CONFIRMATION_TOKEN ADD COLUMN activation timestamp;
